### ISSUE TITLE
Add improved footer

### ISSUE THREAD

**Issue by YashCyanide** [YashCyanide/Remedy#1]
![image](https://github.com/YashCyanide/Remedy/assets/103525833/f4352923-7b56-4690-9e97-f2b459c668bc)
This is a current status of the Footer, Improve footer using html and css only

**Comment by shreyanshig** [comment]
Hi @YashCyanide, Could you please assign this task to me?

**Comment by YashCyanide** [comment]
@shreyanshig , I am Assigning this task to you. try to use only html and css.

**Comment by rohanpra03** [comment]
hi yash , i  want to contribute to you project how can i proceed further?

**Comment by YashCyanide** [comment]
Hi, @rohanpra03 Sorry but I have Already assigned this task to @shreyanshig.
