### ISSUE TITLE
🩹  The 'viewport' meta element 'content' attribute value should contain 'width=device-width', and the horizontal scroll is an issue

### ISSUE THREAD

**Issue by Shivangbhatnagar237** [YashCyanide/Remedy#10]
### Screenshot:
![image](https://github.com/YashCyanide/Remedy/assets/47966497/01617b32-83f5-4c64-b44c-6bc2874bb320)

### Overflow issue:
![image](https://github.com/YashCyanide/Remedy/assets/47966497/8f653191-4ca7-4568-a7f6-5d1349ee1fa8)

- [x] I'm willing to work on this issue

**Comment by YashCyanide** [comment]
@Shivangbhatnagar237 thanks for your contribution , would like to work in future.
