### ISSUE TITLE
Add a Login Page link it to the login Button

### ISSUE THREAD

**Issue by YashCyanide** [YashCyanide/Remedy#2]

**Comment by Pariharx7** [comment]
Hey, I'd like to work on this issue, can you assign me this issue?

**Comment by YashCyanide** [comment]
ok, I am Assigning this task to you @Pariharx7

**Comment by Pariharx7** [comment]
Thanks, will start working on it from tomorrow onwards.

**Comment by YashCyanide** [comment]
Thanks @Pariharx7
