### ISSUE TITLE
Add a Sticky Navbar Similar Strip at top of Web Page Showing emergency contact detail and address

### ISSUE THREAD

**Issue by YashCyanide** [YashCyanide/Remedy#3]

**Comment by madmecodes** [comment]
I would like to contribute in this repository, please assign this issue to me @YashCyanide .

**Comment by YashCyanide** [comment]
Ok, @Ayush-gupta-dev I am Assigning this to you , please try to do it in 2 days.

**Comment by Ayush-gupta-dev** [comment]
Ok i will submit by today

**Comment by madmecodes** [comment]
@YashCyanide  what should be in emergency contact details and all, sticky navbar already there , please elaborate

**Comment by YashCyanide** [comment]
![image](https://github.com/YashCyanide/Remedy/assets/103525833/3790202f-a5d0-4da1-a7cb-6afe84382774)
try to add a Stripe Similar to Navbar , above it as shown in above image

**Comment by madmecodes** [comment]
This what you want right? you can change color fontsize family text needed as/needed if good reply i will make a PR
@YashCyanide 

![ezgif com-video-to-gif](https://github.com/YashCyanide/Remedy/assets/137040550/9657a891-5c7a-4390-aa46-0ed5a8779b0d)

**Comment by YashCyanide** [comment]
It's ok just increase height (5-10px) before making PR
